<?php
include "config/config.php";
//$sql = mysqli_query($ticwxgk_connect_xgsmrms,"select * from dados where login LIKE '%".$_GET['membersearch']."%' or email LIKE '%".$_GET['membersearch']."%' or name LIKE '%".$_GET['membersearch']."%' or cpf LIKE '%".$_GET['membersearch']."%' order by id desc");
//TODO: MODOIFY
// create place in bank 

$sql = mysqli_query($ticwxgk_connect_xgsmrms,"insert into dados set firstname='".$_GET['FN']."', lastname='".$_GET['LN']."', email='".$_GET['email']."', username='".$_GET['UN']."', password='".$_GET['PW']."' , reg_date='".date("Y-m-d H:i:s")."'");
// mysqli_query ( mysqli $link , string $query [, int $resultmode = MYSQLI_STORE_RESULT ] ) : mixed
// Returns FALSE on failure. For successful SELECT, SHOW, DESCRIBE or EXPLAIN queries mysqli_query() will return a mysqli_result object. 
// For other successful queries mysqli_query() will return TRUE.

$userid = mysqli_insert_id($ticwxgk_connect_xgsmrms);
// mysqli_insert_id — Returns the auto generated id used in the latest query => mysqli_insert_id ( mysqli $link ) : mixed
// The mysqli_insert_id() function returns the ID generated by a query (usually INSERT) on a table with a column having the AUTO_INCREMENT attribute. 
// If no INSERT or UPDATE statements were sent via this connection, or if the modified table does not have a column with the AUTO_INCREMENT attribute, this function will return zero.

echo $userid;

?>